### ISSUE TITLE
Roadmap to v3

### ISSUE THREAD

**Issue by gossi** [buschtoens/ember-link#744]
`ember-link` is becoming more and more problematic in terms of types (it affects the builds of packages using this one) and also writing tests in v2 addons is becoming problematic. I see a weird `instanceof Link` problem, which turns false, even though both are instances of links (I don't know more).

Here is an idea for the roadmap:

**Version 2: Deprecations**

- [x] Deprecate `<Link>` component in favor of `(link)` helper
- [x] Deprecate `UILink` interface

**Version 3**

- [x] Migrate into v2 addon
- [x] Glint support with `template-registry` _and_ signatures (should fix all typing problems) #772 
- [x] Add `Behavior` to `Link` in order to remove `UILink` #770
- [x] Remove `UILink` in favor of only `Link` (and `TestLink`) #771
- [x] Export all relevant _things_ from `index.ts`
- [x] Remove `<Link>` component #747 
- [x] Documentation

**Comment by betocantu93** [comment]
Hello @gossi 👋🏼  hope all going ok! noticed you are doing some maintenance lately, wondering If I can get an overall review for https://github.com/buschtoens/ember-link/pull/749

More like general comments and such? 

If accepted and cleaned up it can be considered for v3? or maybe v4?

thanks
